### ISSUE TITLE
Where should the bot responses go?

### ISSUE THREAD

**Issue by EmbeddedAndroid** [ipsum-network/ips-discord-support-bot#4]
Should we have a dedicated channel for bot responses? Or have responses to specific channels such as price-discussions (price) or masternodes for masternode related queries?

**Comment by dnovacik** [comment]
I'd make it, at least for the time being, like this: if someone calls a command in the channel, it responds to him, if he calls the command from other than the bot-messages channel, it would post it there, but mention the caller.

**Comment by dnovacik** [comment]
We also need to make direct bot messages work, currently it's looking for the botchannel and it will produce null reference (it can't get the channel from message, there is none)
